import * as ed from "@noble/ed25519";
const API="http://localhost:8930";
const DEMO="68756c6c2d64656d6f2d6f776e65722d6b65792d64656d6f2d6f6e6c79212121";
const hx=h=>Uint8Array.from((h.match(/../g)??[]).map(x=>parseInt(x,16)));
const bh=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
const sk=hx(DEMO), actor=bh(await ed.getPublicKeyAsync(sk));
const {nonce}=await fetch(`${API}/api/auth/challenge`).then(r=>r.json());
const sig=bh(await ed.signAsync(new TextEncoder().encode(`hull-login:${nonce}`),sk));
const {token}=await fetch(`${API}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actor,nonce,signature:sig})}).then(r=>r.json());
const H={authorization:`Bearer ${token}`,"content-type":"application/json"};
const st=await fetch(`${API}/api/repos/tankrap/hull/settings`,{headers:H});
console.log("admin settings GET:", st.status);
const cr=await fetch(`${API}/api/repos`,{method:"POST",headers:H,body:JSON.stringify({account:"tankrap",name:"sandbox-demo"})});
console.log("create repo:", cr.status, (await cr.text()).slice(0,100));
const nu=await fetch(`${API}/api/actors`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({handle:"nobody",kind:"human"})}).then(r=>r.json());
const nsk=hx(nu.secret_key); const nactor=bh(await ed.getPublicKeyAsync(nsk));
const {nonce:n2}=await fetch(`${API}/api/auth/challenge`).then(r=>r.json());
const s2=bh(await ed.signAsync(new TextEncoder().encode(`hull-login:${n2}`),nsk));
const {token:t2}=await fetch(`${API}/api/auth/login`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({actor:nactor,nonce:n2,signature:s2})}).then(r=>r.json());
const f=await fetch(`${API}/api/repos/tankrap/hull/settings`,{headers:{authorization:`Bearer ${t2}`}});
console.log("outsider (authed non-member) settings GET:", f.status);
